### ISSUE TITLE
nossdav2018.tex line 54: figure absent

### ISSUE THREAD

**Issue by deshmukhrajvardhan** [dbhat/QUICRetransmissions#1]
figures/mobonerun.png not present in the directory

**Comment by dbhat** [comment]
What branch is this?

**Comment by deshmukhrajvardhan** [comment]
master

**Comment by dbhat** [comment]
For ACM TOMM, please use acm_tomm. Issue fixed in master branch but this only contains the first ACM MM paper.

Thanks
